#!/bin/bash
#
#  Command Line Interface to start all services associated with the kiel-parksensors application
#
#  For this tutorial the commands are merely a convenience script to run docker-compose
#

set -e

curl () {
  docker run --network fiware_default --rm appropriate/curl -s \
    "$@"
  printf "."
}

echo -e "\n\n⏳ Waiting for Context Broker to be available\n"
while [ `docker run --network fiware_default --rm appropriate/curl -s -o /dev/null -w %{http_code} 'http://orion:1026/version'` -eq 000 ]
do
  echo -e "Context Broker HTTP state: " `curl -s -o /dev/null -w %{http_code} 'http://orion:1026/version'` " (waiting for 200)"
  sleep 1
done
printf "⏳ Loading context data "

echo -e " \033[1;32mdone\033[0m"